### ISSUE TITLE
Operation not valid when Querying Predictor on Windows

### ISSUE THREAD

**Issue by jkorn2324** [fxnai/fxn3d#9]
**Issue:** On the first prediction attempt on Windows, I receive an error: "Operation is not valid due to current state of the object" After this first prediction, the rest of the predictions are fine. Logs are attached for more information.

**Expected Output:** There shouldn't be an error.

**Technical Specs:**
Unity Version 2022.3.20f1
Fxn 0.0.30 (from npm package manager)
Platform - Windows (Untested on Mac, iOS, & Android)

**How to Reproduce (In the Unity Editor):**
Step 1: Create a script that loads in a predictor (or use a sample Predictor scene)
Step 2: Disconnect from Internet
Step 3: Run project

Here is the main log I keep receiving from the Editor:
[UnityEditorLogs.txt](https://github.com/user-attachments/files/17528800/UnityEditorLogs.txt)

**Comment by olokobayusuf** [comment]
@jkorn2324 some context:

1. Predictor caching is a runtime-only feature. We never cache predictors in the Editor, which means you'll have to test with live builds.
2. Predictor caching is currently implemented only for Android, iOS, and macOS (i.e. sandboxed platforms). I'm keeping this issue open because we should be able to support Windows. WebGL is handled in a special way, directly in the browser (not Unity).

Thanks for testing it out with quick turnaround.

**Comment by olokobayusuf** [comment]
We're implementing full caching in the next release, 0.0.32. That will fix this issue.

**Comment by olokobayusuf** [comment]
[Function now performs full caching](https://github.com/fxnai/fxn3d/releases/tag/0.0.32).
